name: Production deploy

on:
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - deploy-production

env:
  CONTENT_ISLAND_SECRET_TOKEN: ${{ secrets.CONTENT_ISLAND_SECRET_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://gentle-forest-01f461703.3.azurestaticapps.net

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_WAVE_06AC07403 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: 'dist'
          output_location: 'dist'
          skip_app_build: true
          skip_api_build: true
        env:
          NODE_VERSION: 22.21.0
